package mru.tsc.model;

public class Figures extends ToyFormatting {
	
	/*
	 * This class is used to create figures objects
	 * The Classification can either be Action, Doll, Or Historic
	 * A, D, H
	 */
	char classification;
	
	/**
	 * Constructor used to create the Figures object.
	 * Arguments from the ToyFormatting superclass
	 * 
	 * @param SN
	 * @param name
	 * @param brand
	 * @param price
	 * @param availableCount
	 * @param ageAppropriate
	 * @param type
	 * @param type
	 */
	public Figures(String SN, String name, String brand, double price, int availableCount, int ageAppropriate, String classification) {
		super(SN, name, brand, price, availableCount, ageAppropriate);
		this.classification = classification.charAt(0);
	}

	//Getter And Setters generated by Eclipse
	public char getClassification() {
		return classification;
	}

	public void setClassification(char classification) {
		this.classification = classification;
	}
	
	// Formats the output that is displayed to user 
	public String toString() {
		return "Category:Figure, Serial Number: " + SN + ", Name: " + name + ", Brand: " + brand +
				", Price: " + price + ", Available Count: " + availableCount + ", Age Appropriate: " + ageAppropriate +
				", Classification: " + classification;
	}
	
	// This method creates the format for the Figure class
	public String format() {
		return SN + ";" + name + ";" + brand + ";" + price + ";" + availableCount + ";" + ageAppropriate + ";" + classification;
	}
}
