package mru.tsc.model;

public abstract class ToyFormatting {
	
	/**
	 * An Abstract class 
	 * Provides a constructor
	 * As well as getters and setters
	 * The superclass for all toy types
	 */
	String SN;
	String name;
	String brand;
	double price;
	int ageAppropriate;
	int availableCount;
	
	/**
	 * This method is the constructor for the arguments shared between the toy 
	 * types classes (figures, puzzles, board games, animals)
	 * 
	 * @param SN
	 * @param name
	 * @param brand
	 * @param price
	 * @param availableCount
	 * @param ageAppropriate
	 */
	
	public ToyFormatting(String SN, String name, String brand, double price, int availableCount, int ageAppropriate) {
		this.SN = SN;
		this.name = name;
		this.brand = brand;
		this.price = price;
		this.availableCount = availableCount;
		this.ageAppropriate = ageAppropriate;
	}

	/**
	 * Getters and setters generated by Eclipse
	 * 
	 */
	public String getSN() {
		return SN;
	}

	public void setSN(String sN) {
		SN = sN;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getAgeAppropriate() {
		return ageAppropriate;
	}

	public void setAgeAppropriate(int ageAppropriate) {
		this.ageAppropriate = ageAppropriate;
	}

	public int getAvailableCount() {
		return availableCount;
	}

	public void setAvailableCount(int availableCount) {
		this.availableCount = availableCount;
	}
}
